name: Release CI

on:
  workflow_dispatch: # Enables manual "Run workflow" button in GitHub UI
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current tag or fallback
        id: tag
        run: |
          TAG=${GITHUB_REF_NAME}
          if [ "$TAG" = "main" ] || [ -z "$TAG" ]; then
            TAG="latest"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push client release
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client.production
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/your_spotify_client:latest
            ghcr.io/${{ github.repository_owner }}/your_spotify_client:${{ steps.tag.outputs.tag }}

      - name: Build and push server release
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server.production
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/your_spotify_server:latest
            ghcr.io/${{ github.repository_owner }}/your_spotify_server:${{ steps.tag.outputs.tag }}
